# Review Calls #

@base_url=http://34.77.228.196:3000/api/reviews

###
GET {{base_url}}

###
GET {{base_url}}/64c0f5646f01501c3cf29efe

###

POST {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc

{
  "shirt": "64bfa61412bc3fa297a192c6",
  "rating": 5,
  "comment": "This is great!!"
}

###
PUT {{base_url}}/64d0c8e2c469d785d76f222a
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc

{
  "shirt": "64bfa61412bc3fa297a192c6",
  "rating": 5,
  "comment": "This shirt is perfect!"
}

###
DELETE {{base_url}}/64bfde85a59898842a8c3bdf
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc