# Categorie calls #


@base_url=http://34.77.228.196:3000/api/categories

get {{base_url}}

###
get {{base_url}}/64c0664379b3e4596e917e24

###

POST {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc

{
  "naam": "Herfst",
  "beschrijving": "Herfst Collectie"
}

###
PUT {{base_url}}/64cf87a0c469d785d76f2196
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTE0MDMzMjN9.HxLlpCwXCJI18MJ84-Emcv8wIEyXFnGHTsSaHq3ZvJM

{
  "naam": "Winter2",
  "beschrijving": "Winter2 Collectie"
}


### 
DELETE {{base_url}}/64c0664379b3e4596e917e24
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTE0MDMzMjN9.HxLlpCwXCJI18MJ84-Emcv8wIEyXFnGHTsSaHq3ZvJM
