# Shirt Calls #


@base_url=http://34.77.228.196:3000/api/shirts

get {{base_url}}

###
get {{base_url}}/64bfa64012bc3fa297a192c8


###

POST {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc

{
    "naam": "Voetbal T-Shirt", 
    "beschrijving": "Voetbal T-shirt Rode Duivels",
    "prijs": 49.99, 
    "categorie": "64bed75a77a492a9c226e26f", 
    "maten": ["S", "M", "L"], 
    "kleuren": ["Rood", "Blauw", "Wit"]
}


###

PUT {{base_url}}/64c0f59c6f01501c3cf29f03
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc

{
    "naam": "Jongens Voetbal T-Shirt", 
    "beschrijving": "Voetbal T-shirt Rode Duivels",
    "prijs": 49.99, 
    "categorie": "64bed75a77a492a9c226e26f", 
    "maten": ["S", "M", "L"], 
    "kleuren": ["Rood", "Blauw", "Wit"]
}

###
delete {{base_url}}/64c03d3bafe8b4bb920355e2
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMwNjVjZTc5YjNlNDU5NmU5MTdlMWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTAzNjcwNzZ9.JBTKNtbrdztoyxmIEoJ_rtwEB5qrhdBKyIOAfnkZquc
